/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ConnectRaycastRouteImport } from './routes/connect-raycast'
import { Route as ConnectExtensionRouteImport } from './routes/connect-extension'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareSlugRouteImport } from './routes/share/$slug'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ApiSentryTunnelRouteImport } from './routes/api/sentry-tunnel'
import { Route as ApiInlineAiRouteImport } from './routes/api/inline-ai'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceWorkspaceWorkspaceIdRouteRouteImport } from './routes/_workspace/workspace/$workspaceId/route'
import { Route as WorkspaceWorkspaceWorkspaceIdIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/index'
import { Route as WorkspaceWorkspaceWorkspaceIdTrashRouteImport } from './routes/_workspace/workspace/$workspaceId/trash'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsRouteImport } from './routes/_workspace/workspace/$workspaceId/tags'
import { Route as WorkspaceWorkspaceWorkspaceIdSettingsRouteImport } from './routes/_workspace/workspace/$workspaceId/settings'
import { Route as WorkspaceWorkspaceWorkspaceIdSearchRouteImport } from './routes/_workspace/workspace/$workspaceId/search'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport } from './routes/_workspace/workspace/$workspaceId/library/route'
import { Route as WorkspaceWorkspaceWorkspaceIdChatRouteRouteImport } from './routes/_workspace/workspace/$workspaceId/chat/route'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/tags/index'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/library/index'
import { Route as WorkspaceWorkspaceWorkspaceIdJournalIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/journal/index'
import { Route as WorkspaceWorkspaceWorkspaceIdChatIndexRouteImport } from './routes/_workspace/workspace/$workspaceId/chat/index'
import { Route as WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport } from './routes/_workspace/workspace/$workspaceId/tags/$tagName'
import { Route as WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport } from './routes/_workspace/workspace/$workspaceId/resource/$resourceId'
import { Route as WorkspaceWorkspaceWorkspaceIdJournalDateRouteImport } from './routes/_workspace/workspace/$workspaceId/journal/$date'
import { Route as WorkspaceWorkspaceWorkspaceIdChatThreadIdRouteImport } from './routes/_workspace/workspace/$workspaceId/chat/$threadId'
import { Route as WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport } from './routes/_workspace/workspace/$workspaceId/library/collection/$collectionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRaycastRoute = ConnectRaycastRouteImport.update({
  id: '/connect-raycast',
  path: '/connect-raycast',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectExtensionRoute = ConnectExtensionRouteImport.update({
  id: '/connect-extension',
  path: '/connect-extension',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareSlugRoute = ShareSlugRouteImport.update({
  id: '/share/$slug',
  path: '/share/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSentryTunnelRoute = ApiSentryTunnelRouteImport.update({
  id: '/api/sentry-tunnel',
  path: '/api/sentry-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInlineAiRoute = ApiInlineAiRouteImport.update({
  id: '/api/inline-ai',
  path: '/api/inline-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceWorkspaceWorkspaceIdRouteRoute =
  WorkspaceWorkspaceWorkspaceIdRouteRouteImport.update({
    id: '/workspace/$workspaceId',
    path: '/workspace/$workspaceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdIndexRoute =
  WorkspaceWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTrashRoute =
  WorkspaceWorkspaceWorkspaceIdTrashRouteImport.update({
    id: '/trash',
    path: '/trash',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsRoute =
  WorkspaceWorkspaceWorkspaceIdTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdSettingsRoute =
  WorkspaceWorkspaceWorkspaceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdSearchRoute =
  WorkspaceWorkspaceWorkspaceIdSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdChatRouteRoute =
  WorkspaceWorkspaceWorkspaceIdChatRouteRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsIndexRoute =
  WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdTagsRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdJournalIndexRoute =
  WorkspaceWorkspaceWorkspaceIdJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdChatIndexRoute =
  WorkspaceWorkspaceWorkspaceIdChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdChatRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute =
  WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport.update({
    id: '/$tagName',
    path: '/$tagName',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdTagsRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute =
  WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport.update({
    id: '/resource/$resourceId',
    path: '/resource/$resourceId',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdJournalDateRoute =
  WorkspaceWorkspaceWorkspaceIdJournalDateRouteImport.update({
    id: '/journal/$date',
    path: '/journal/$date',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute =
  WorkspaceWorkspaceWorkspaceIdChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdChatRouteRoute,
  } as any)
const WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute =
  WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/connect-extension': typeof ConnectExtensionRoute
  '/connect-raycast': typeof ConnectRaycastRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inline-ai': typeof ApiInlineAiRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$slug': typeof ShareSlugRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatRouteRouteWithChildren
  '/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  '/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  '/workspace/$workspaceId/trash': typeof WorkspaceWorkspaceWorkspaceIdTrashRoute
  '/workspace/$workspaceId/': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/chat/$threadId': typeof WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute
  '/workspace/$workspaceId/journal/$date': typeof WorkspaceWorkspaceWorkspaceIdJournalDateRoute
  '/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/workspace/$workspaceId/chat/': typeof WorkspaceWorkspaceWorkspaceIdChatIndexRoute
  '/workspace/$workspaceId/journal/': typeof WorkspaceWorkspaceWorkspaceIdJournalIndexRoute
  '/workspace/$workspaceId/library/': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/workspace/$workspaceId/tags/': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/connect-extension': typeof ConnectExtensionRoute
  '/connect-raycast': typeof ConnectRaycastRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AppSettingsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inline-ai': typeof ApiInlineAiRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$slug': typeof ShareSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/workspace/$workspaceId/trash': typeof WorkspaceWorkspaceWorkspaceIdTrashRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/chat/$threadId': typeof WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute
  '/workspace/$workspaceId/journal/$date': typeof WorkspaceWorkspaceWorkspaceIdJournalDateRoute
  '/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatIndexRoute
  '/workspace/$workspaceId/journal': typeof WorkspaceWorkspaceWorkspaceIdJournalIndexRoute
  '/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/connect-extension': typeof ConnectExtensionRoute
  '/connect-raycast': typeof ConnectRaycastRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/inline-ai': typeof ApiInlineAiRoute
  '/api/sentry-tunnel': typeof ApiSentryTunnelRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$slug': typeof ShareSlugRoute
  '/_workspace/workspace/$workspaceId': typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_workspace/workspace/$workspaceId/chat': typeof WorkspaceWorkspaceWorkspaceIdChatRouteRouteWithChildren
  '/_workspace/workspace/$workspaceId/library': typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  '/_workspace/workspace/$workspaceId/search': typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  '/_workspace/workspace/$workspaceId/settings': typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  '/_workspace/workspace/$workspaceId/tags': typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  '/_workspace/workspace/$workspaceId/trash': typeof WorkspaceWorkspaceWorkspaceIdTrashRoute
  '/_workspace/workspace/$workspaceId/': typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  '/_workspace/workspace/$workspaceId/chat/$threadId': typeof WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute
  '/_workspace/workspace/$workspaceId/journal/$date': typeof WorkspaceWorkspaceWorkspaceIdJournalDateRoute
  '/_workspace/workspace/$workspaceId/resource/$resourceId': typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  '/_workspace/workspace/$workspaceId/tags/$tagName': typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  '/_workspace/workspace/$workspaceId/chat/': typeof WorkspaceWorkspaceWorkspaceIdChatIndexRoute
  '/_workspace/workspace/$workspaceId/journal/': typeof WorkspaceWorkspaceWorkspaceIdJournalIndexRoute
  '/_workspace/workspace/$workspaceId/library/': typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  '/_workspace/workspace/$workspaceId/tags/': typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
  '/_workspace/workspace/$workspaceId/library/collection/$collectionId': typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/connect-extension'
    | '/connect-raycast'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/api/chat'
    | '/api/inline-ai'
    | '/api/sentry-tunnel'
    | '/invite/$token'
    | '/share/$slug'
    | '/workspace/$workspaceId'
    | '/api/auth/$'
    | '/workspace/$workspaceId/chat'
    | '/workspace/$workspaceId/library'
    | '/workspace/$workspaceId/search'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/tags'
    | '/workspace/$workspaceId/trash'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/chat/$threadId'
    | '/workspace/$workspaceId/journal/$date'
    | '/workspace/$workspaceId/resource/$resourceId'
    | '/workspace/$workspaceId/tags/$tagName'
    | '/workspace/$workspaceId/chat/'
    | '/workspace/$workspaceId/journal/'
    | '/workspace/$workspaceId/library/'
    | '/workspace/$workspaceId/tags/'
    | '/workspace/$workspaceId/library/collection/$collectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/connect-extension'
    | '/connect-raycast'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/api/chat'
    | '/api/inline-ai'
    | '/api/sentry-tunnel'
    | '/invite/$token'
    | '/share/$slug'
    | '/api/auth/$'
    | '/workspace/$workspaceId/search'
    | '/workspace/$workspaceId/settings'
    | '/workspace/$workspaceId/trash'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/chat/$threadId'
    | '/workspace/$workspaceId/journal/$date'
    | '/workspace/$workspaceId/resource/$resourceId'
    | '/workspace/$workspaceId/tags/$tagName'
    | '/workspace/$workspaceId/chat'
    | '/workspace/$workspaceId/journal'
    | '/workspace/$workspaceId/library'
    | '/workspace/$workspaceId/tags'
    | '/workspace/$workspaceId/library/collection/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/_app'
    | '/_auth'
    | '/_workspace'
    | '/connect-extension'
    | '/connect-raycast'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/api/chat'
    | '/api/inline-ai'
    | '/api/sentry-tunnel'
    | '/invite/$token'
    | '/share/$slug'
    | '/_workspace/workspace/$workspaceId'
    | '/api/auth/$'
    | '/_workspace/workspace/$workspaceId/chat'
    | '/_workspace/workspace/$workspaceId/library'
    | '/_workspace/workspace/$workspaceId/search'
    | '/_workspace/workspace/$workspaceId/settings'
    | '/_workspace/workspace/$workspaceId/tags'
    | '/_workspace/workspace/$workspaceId/trash'
    | '/_workspace/workspace/$workspaceId/'
    | '/_workspace/workspace/$workspaceId/chat/$threadId'
    | '/_workspace/workspace/$workspaceId/journal/$date'
    | '/_workspace/workspace/$workspaceId/resource/$resourceId'
    | '/_workspace/workspace/$workspaceId/tags/$tagName'
    | '/_workspace/workspace/$workspaceId/chat/'
    | '/_workspace/workspace/$workspaceId/journal/'
    | '/_workspace/workspace/$workspaceId/library/'
    | '/_workspace/workspace/$workspaceId/tags/'
    | '/_workspace/workspace/$workspaceId/library/collection/$collectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ConnectExtensionRoute: typeof ConnectExtensionRoute
  ConnectRaycastRoute: typeof ConnectRaycastRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInlineAiRoute: typeof ApiInlineAiRoute
  ApiSentryTunnelRoute: typeof ApiSentryTunnelRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ShareSlugRoute: typeof ShareSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-raycast': {
      id: '/connect-raycast'
      path: '/connect-raycast'
      fullPath: '/connect-raycast'
      preLoaderRoute: typeof ConnectRaycastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-extension': {
      id: '/connect-extension'
      path: '/connect-extension'
      fullPath: '/connect-extension'
      preLoaderRoute: typeof ConnectExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$slug': {
      id: '/share/$slug'
      path: '/share/$slug'
      fullPath: '/share/$slug'
      preLoaderRoute: typeof ShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sentry-tunnel': {
      id: '/api/sentry-tunnel'
      path: '/api/sentry-tunnel'
      fullPath: '/api/sentry-tunnel'
      preLoaderRoute: typeof ApiSentryTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inline-ai': {
      id: '/api/inline-ai'
      path: '/api/inline-ai'
      fullPath: '/api/inline-ai'
      preLoaderRoute: typeof ApiInlineAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/workspace/$workspaceId': {
      id: '/_workspace/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/workspace/$workspaceId/': {
      id: '/_workspace/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/trash': {
      id: '/_workspace/workspace/$workspaceId/trash'
      path: '/trash'
      fullPath: '/workspace/$workspaceId/trash'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTrashRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags': {
      id: '/_workspace/workspace/$workspaceId/tags'
      path: '/tags'
      fullPath: '/workspace/$workspaceId/tags'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/settings': {
      id: '/_workspace/workspace/$workspaceId/settings'
      path: '/settings'
      fullPath: '/workspace/$workspaceId/settings'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdSettingsRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/search': {
      id: '/_workspace/workspace/$workspaceId/search'
      path: '/search'
      fullPath: '/workspace/$workspaceId/search'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdSearchRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/library': {
      id: '/_workspace/workspace/$workspaceId/library'
      path: '/library'
      fullPath: '/workspace/$workspaceId/library'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/chat': {
      id: '/_workspace/workspace/$workspaceId/chat'
      path: '/chat'
      fullPath: '/workspace/$workspaceId/chat'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRouteRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags/': {
      id: '/_workspace/workspace/$workspaceId/tags/'
      path: '/'
      fullPath: '/workspace/$workspaceId/tags/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRoute
    }
    '/_workspace/workspace/$workspaceId/library/': {
      id: '/_workspace/workspace/$workspaceId/library/'
      path: '/'
      fullPath: '/workspace/$workspaceId/library/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute
    }
    '/_workspace/workspace/$workspaceId/journal/': {
      id: '/_workspace/workspace/$workspaceId/journal/'
      path: '/journal'
      fullPath: '/workspace/$workspaceId/journal/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdJournalIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/chat/': {
      id: '/_workspace/workspace/$workspaceId/chat/'
      path: '/'
      fullPath: '/workspace/$workspaceId/chat/'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdChatIndexRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRouteRoute
    }
    '/_workspace/workspace/$workspaceId/tags/$tagName': {
      id: '/_workspace/workspace/$workspaceId/tags/$tagName'
      path: '/$tagName'
      fullPath: '/workspace/$workspaceId/tags/$tagName'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRoute
    }
    '/_workspace/workspace/$workspaceId/resource/$resourceId': {
      id: '/_workspace/workspace/$workspaceId/resource/$resourceId'
      path: '/resource/$resourceId'
      fullPath: '/workspace/$workspaceId/resource/$resourceId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/journal/$date': {
      id: '/_workspace/workspace/$workspaceId/journal/$date'
      path: '/journal/$date'
      fullPath: '/workspace/$workspaceId/journal/$date'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdJournalDateRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRoute
    }
    '/_workspace/workspace/$workspaceId/chat/$threadId': {
      id: '/_workspace/workspace/$workspaceId/chat/$threadId'
      path: '/$threadId'
      fullPath: '/workspace/$workspaceId/chat/$threadId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdChatThreadIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRouteRoute
    }
    '/_workspace/workspace/$workspaceId/library/collection/$collectionId': {
      id: '/_workspace/workspace/$workspaceId/library/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/workspace/$workspaceId/library/collection/$collectionId'
      preLoaderRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRouteImport
      parentRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface WorkspaceWorkspaceWorkspaceIdChatRouteRouteChildren {
  WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute: typeof WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute
  WorkspaceWorkspaceWorkspaceIdChatIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdChatIndexRoute
}

const WorkspaceWorkspaceWorkspaceIdChatRouteRouteChildren: WorkspaceWorkspaceWorkspaceIdChatRouteRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute:
      WorkspaceWorkspaceWorkspaceIdChatThreadIdRoute,
    WorkspaceWorkspaceWorkspaceIdChatIndexRoute:
      WorkspaceWorkspaceWorkspaceIdChatIndexRoute,
  }

const WorkspaceWorkspaceWorkspaceIdChatRouteRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdChatRouteRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdChatRouteRouteChildren,
  )

interface WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren {
  WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute
  WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute
}

const WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren: WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryIndexRoute,
    WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryCollectionCollectionIdRoute,
  }

const WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteChildren,
  )

interface WorkspaceWorkspaceWorkspaceIdTagsRouteChildren {
  WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute
  WorkspaceWorkspaceWorkspaceIdTagsIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsIndexRoute
}

const WorkspaceWorkspaceWorkspaceIdTagsRouteChildren: WorkspaceWorkspaceWorkspaceIdTagsRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute:
      WorkspaceWorkspaceWorkspaceIdTagsTagNameRoute,
    WorkspaceWorkspaceWorkspaceIdTagsIndexRoute:
      WorkspaceWorkspaceWorkspaceIdTagsIndexRoute,
  }

const WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdTagsRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdTagsRouteChildren,
  )

interface WorkspaceWorkspaceWorkspaceIdRouteRouteChildren {
  WorkspaceWorkspaceWorkspaceIdChatRouteRoute: typeof WorkspaceWorkspaceWorkspaceIdChatRouteRouteWithChildren
  WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute: typeof WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren
  WorkspaceWorkspaceWorkspaceIdSearchRoute: typeof WorkspaceWorkspaceWorkspaceIdSearchRoute
  WorkspaceWorkspaceWorkspaceIdSettingsRoute: typeof WorkspaceWorkspaceWorkspaceIdSettingsRoute
  WorkspaceWorkspaceWorkspaceIdTagsRoute: typeof WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren
  WorkspaceWorkspaceWorkspaceIdTrashRoute: typeof WorkspaceWorkspaceWorkspaceIdTrashRoute
  WorkspaceWorkspaceWorkspaceIdIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdIndexRoute
  WorkspaceWorkspaceWorkspaceIdJournalDateRoute: typeof WorkspaceWorkspaceWorkspaceIdJournalDateRoute
  WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute: typeof WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute
  WorkspaceWorkspaceWorkspaceIdJournalIndexRoute: typeof WorkspaceWorkspaceWorkspaceIdJournalIndexRoute
}

const WorkspaceWorkspaceWorkspaceIdRouteRouteChildren: WorkspaceWorkspaceWorkspaceIdRouteRouteChildren =
  {
    WorkspaceWorkspaceWorkspaceIdChatRouteRoute:
      WorkspaceWorkspaceWorkspaceIdChatRouteRouteWithChildren,
    WorkspaceWorkspaceWorkspaceIdLibraryRouteRoute:
      WorkspaceWorkspaceWorkspaceIdLibraryRouteRouteWithChildren,
    WorkspaceWorkspaceWorkspaceIdSearchRoute:
      WorkspaceWorkspaceWorkspaceIdSearchRoute,
    WorkspaceWorkspaceWorkspaceIdSettingsRoute:
      WorkspaceWorkspaceWorkspaceIdSettingsRoute,
    WorkspaceWorkspaceWorkspaceIdTagsRoute:
      WorkspaceWorkspaceWorkspaceIdTagsRouteWithChildren,
    WorkspaceWorkspaceWorkspaceIdTrashRoute:
      WorkspaceWorkspaceWorkspaceIdTrashRoute,
    WorkspaceWorkspaceWorkspaceIdIndexRoute:
      WorkspaceWorkspaceWorkspaceIdIndexRoute,
    WorkspaceWorkspaceWorkspaceIdJournalDateRoute:
      WorkspaceWorkspaceWorkspaceIdJournalDateRoute,
    WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute:
      WorkspaceWorkspaceWorkspaceIdResourceResourceIdRoute,
    WorkspaceWorkspaceWorkspaceIdJournalIndexRoute:
      WorkspaceWorkspaceWorkspaceIdJournalIndexRoute,
  }

const WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren =
  WorkspaceWorkspaceWorkspaceIdRouteRoute._addFileChildren(
    WorkspaceWorkspaceWorkspaceIdRouteRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceWorkspaceWorkspaceIdRouteRoute: typeof WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceWorkspaceWorkspaceIdRouteRoute:
    WorkspaceWorkspaceWorkspaceIdRouteRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ConnectExtensionRoute: ConnectExtensionRoute,
  ConnectRaycastRoute: ConnectRaycastRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInlineAiRoute: ApiInlineAiRoute,
  ApiSentryTunnelRoute: ApiSentryTunnelRoute,
  InviteTokenRoute: InviteTokenRoute,
  ShareSlugRoute: ShareSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
