import {
  RiBookOpenFill,
  RiBookShelfFill,
  RiBox1Fill,
  RiBriefcaseFill,
  RiCodeFill,
  RiCompassFill,
  RiCupFill,
  RiDatabaseFill,
  RiFlashlightFill,
  RiFocus3Fill,
  RiFolderFill,
  RiGlobeFill,
  RiHeartFill,
  RiHomeFill,
  RiLightbulbFill,
  RiMusicFill,
  RiPaletteFill,
  RiPenNibFill,
  RiRocketFill,
  RiSchoolFill,
  RiShieldFill,
  RiSparklingFill,
  RiStackFill,
  RiStarFill,
} from "@remixicon/react";
export const workspaceIcons = [
  { name: "box", icon: RiBox1Fill },
  { name: "folder", icon: RiFolderFill },
  { name: "book", icon: RiBookOpenFill },
  { name: "briefcase", icon: RiBriefcaseFill },
  { name: "code", icon: RiCodeFill },
  { name: "globe", icon: RiGlobeFill },
  { name: "home", icon: RiHomeFill },
  { name: "layers", icon: RiStackFill },
  { name: "library", icon: RiBookShelfFill },
  { name: "lightbulb", icon: RiLightbulbFill },
  { name: "rocket", icon: RiRocketFill },
  { name: "sparkles", icon: RiSparklingFill },
  { name: "star", icon: RiStarFill },
  { name: "zap", icon: RiFlashlightFill },
  { name: "target", icon: RiFocus3Fill },
  { name: "compass", icon: RiCompassFill },
  { name: "palette", icon: RiPaletteFill },
  { name: "pen-tool", icon: RiPenNibFill },
  { name: "database", icon: RiDatabaseFill },
  { name: "shield", icon: RiShieldFill },
  { name: "heart", icon: RiHeartFill },
  { name: "coffee", icon: RiCupFill },
  { name: "music", icon: RiMusicFill },
  { name: "school", icon: RiSchoolFill },
] as const;

export type WorkspaceIconName = (typeof workspaceIcons)[number]["name"];

export const getWorkspaceIcon = (name?: string) =>
  workspaceIcons.find((i) => i.name === name)?.icon ?? RiBox1Fill;
