import {
  RiBookmarkFill,
  RiBookOpenFill,
  RiBookShelfFill,
  RiBox1Fill,
  RiBrainFill,
  RiBriefcaseFill,
  RiBuilding2Fill,
  RiCalendarFill,
  RiCameraFill,
  RiChat3Fill,
  RiCodeFill,
  RiCompassFill,
  RiCupFill,
  RiDatabaseFill,
  RiFireFill,
  RiFlag2Fill,
  RiFlashlightFill,
  RiFlaskFill,
  RiFocus3Fill,
  RiFolderFill,
  RiGlobeFill,
  RiHandHeartFill,
  RiHeartFill,
  RiHomeFill,
  RiImageFill,
  RiKey2Fill,
  RiLeafFill,
  RiLightbulbFill,
  RiMagicFill,
  RiMapPinFill,
  RiMicFill,
  RiMoneyDollarCircleFill,
  RiMusicFill,
  RiPaintBrushFill,
  RiPaletteFill,
  RiPenNibFill,
  RiPlaneFill,
  RiPlanetFill,
  RiPriceTag3Fill,
  RiPushpinFill,
  RiPuzzleFill,
  RiRocketFill,
  RiSchoolFill,
  RiShieldFill,
  RiSparklingFill,
  RiStackFill,
  RiStarFill,
  RiTeamFill,
  RiToolsFill,
  RiTrophyFill,
} from "@remixicon/react";

export const workspaceIcons = [
  { name: "box", icon: RiBox1Fill },
  { name: "folder", icon: RiFolderFill },
  { name: "book", icon: RiBookOpenFill },
  { name: "briefcase", icon: RiBriefcaseFill },
  { name: "code", icon: RiCodeFill },
  { name: "globe", icon: RiGlobeFill },
  { name: "home", icon: RiHomeFill },
  { name: "layers", icon: RiStackFill },
  { name: "library", icon: RiBookShelfFill },
  { name: "lightbulb", icon: RiLightbulbFill },
  { name: "rocket", icon: RiRocketFill },
  { name: "sparkles", icon: RiSparklingFill },
  { name: "star", icon: RiStarFill },
  { name: "zap", icon: RiFlashlightFill },
  { name: "target", icon: RiFocus3Fill },
  { name: "compass", icon: RiCompassFill },
  { name: "plane", icon: RiPlaneFill },
  { name: "palette", icon: RiPaletteFill },
  { name: "pen-tool", icon: RiPenNibFill },
  { name: "database", icon: RiDatabaseFill },
  { name: "shield", icon: RiShieldFill },
  { name: "heart", icon: RiHeartFill },
  { name: "coffee", icon: RiCupFill },
  { name: "music", icon: RiMusicFill },
  { name: "school", icon: RiSchoolFill },
  { name: "bookmark", icon: RiBookmarkFill },
  { name: "flag", icon: RiFlag2Fill },
  { name: "pin", icon: RiPushpinFill },
  { name: "tag", icon: RiPriceTag3Fill },
  { name: "trophy", icon: RiTrophyFill },
  { name: "calendar", icon: RiCalendarFill },
  { name: "building", icon: RiBuilding2Fill },
  { name: "team", icon: RiTeamFill },
  { name: "chat", icon: RiChat3Fill },
  { name: "brain", icon: RiBrainFill },
  { name: "flask", icon: RiFlaskFill },
  { name: "magic", icon: RiMagicFill },
  { name: "planet", icon: RiPlanetFill },
  { name: "map-pin", icon: RiMapPinFill },
  { name: "key", icon: RiKey2Fill },
  { name: "puzzle", icon: RiPuzzleFill },
  { name: "leaf", icon: RiLeafFill },
  { name: "fire", icon: RiFireFill },
  { name: "camera", icon: RiCameraFill },
  { name: "mic", icon: RiMicFill },
  { name: "image", icon: RiImageFill },
  { name: "paint-brush", icon: RiPaintBrushFill },
  { name: "hand-heart", icon: RiHandHeartFill },
  { name: "money", icon: RiMoneyDollarCircleFill },
  { name: "tools", icon: RiToolsFill },
] as const;

export type WorkspaceIconName = (typeof workspaceIcons)[number]["name"];

export const getWorkspaceIcon = (name?: string) =>
  workspaceIcons.find((i) => i.name === name)?.icon ?? RiBox1Fill;
